keys:
  public: f0a592aa4f57d72d1ed789abce9d649b
  private: 239f9020271702b9f750d4474bff9207
fallback: 1
languages_expected:
  - ''
test_mode:
  enabled: false
  api_endpoint: dev.mollom.com
  keys:
    public: ''
    private: ''
  invalid:
    api_endpoint: fake-host
privacy_link: true
log_level: 4
connection_timeout_seconds: 3
api_endpoint: rest.mollom.com
captcha:
  audio:
    enabled: true
_core:
  default_config_hash: 8uHhdqIc3ARJWLcZ_gKimtOymT0SRxGryuDcC6S5Vx4
